projects/myboard/board/urls.py
from django.urls import path

from.import views
app_name = 'board'
urlpatterns = [
    # board/라면
    path('', views.index, name='index'),
    # 글읽기 주소 /board/0
    path('<int:id>/', views.read, name='detail'),
    # 글쓰기 주소
    path('write/', views.write, name='write'),
    # 수정 주소
    path('<int:id>/update/', views.update, name='update'),
    # 삭제 주소
    path('<int:id>/delete/', views.delete, name='delete'),
    # 댓글쓰기 주소
    path('<int:id>/write_reply/', views.write_reply, name = 'write_reply'),
    # 댓글 삭제 주소(id: 글번호, rid: 댓글번호)
    path('<int:id>/delete_reply/', views.delete_reply, name='delete_reply'),
    # 댓글 수정 주소
    path('<int:id>/update_reply/', views.update_reply, name='update_reply'),

    # AJAX
    path('callAjax/', views.call_ajax),
    
    # AJAX_댓글 목록
    path('<int:id>/load_reply/',views.load_reply, name = 'load_reply'),
    path('<int:id>/downlad/',views.downlad,name='downlad'),


    # CBV 방식으로 호출할 주소
    # as_view() : 클래스를 뷰의 기능으로서 사용하겠다~
    path('cbv/', views.BoardList.as_view()),
    path('cbv/<int:pk>/', views.BoardDetail.as_view()),
]

projects/myboard/myboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings # 현재 프로젝트의 sttings.py
from django.conf.urls.static import static

urlpatterns = [
    path('', include('common.urls')),
    path("admin/", admin.site.urls),
    path('board/', include('board.urls')),
    
] + static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

projects/myboard/board/models.py
from django.db import models
from django.utils import timezone  # 시간 정보에 관한 모듈
from django.contrib.auth.models import User # auth_user 테이블과 매핑되는 모델

# Create your models here.

class Board(models.Model):
    # 번호는 pk설정 안하면 장고가 자동으로 id부여해줌
    #### 필드와 필드 사이에 ','금지 ####
    title = models.CharField(max_length= 100)  # 제목
    content = models.TextField(null=False, blank=False)  # 내용
    # writer = models.CharField(max_length=10)  # 작성자
    input_date = models.DateTimeField(default=timezone.now)  # 작성일
    view_count = models.IntegerField(default=0)  # 조회수
    # DB에는 필드이름_기본키 이름으로 열이 생성됨
    author = models.ForeignKey(User,on_delete=models.CASCADE)

    # 파일첨부 관련 필드
    attached_file = models.FileField(upload_to='board/%Y-%m-%d/',null=True)
    original_file_name =models.CharField(max_length=260, null =True)

    # Java의 toString이랑 비슷하게
    # 객체정보를 문자열로 돌려줌
    def __str__(self) :
        return f"{self.id} ~ {self.title}~"

# 댓글 정보를 포함하는 모델
class Reply(models.Model) :
    # pk : 장고가 알아서 만들어 줄것임(id)
    # 게시글번호(fk)
    board_obj = models.ForeignKey(Board, on_delete=models.CASCADE)
    # 사용자(fk)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # 댓글내용
    reply_content = models.TextField(null = False, blank = False)
    # 작성시간
    input_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.reply_content

projects/myboard/board/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,JsonResponse,HttpResponse,FileResponse
from django.core.paginator import Paginator
from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView
from .models import Board, Reply
# Create your views here.
from json import loads
# 게시판 목록보기
def index(request):
    print('index() 실행 ')

    # 반환되는 queryset에 대해서 order_by함수 이용하면 특정 필드 기준으로 정렬
    # order_by에 들어가는 필드 이름 앞에 -를 붙이면 내림차순(DESC) 아니면 오름차순(ASC)
    result = None # 필터링된 리스트
    context = {}
    
    # request.GET : get방식으로 보낸 데이터들을 딕셔너리 타입으로 저장
    # print(request.GET)

    # 검색 조건과 검색 키워드가 있어야 필터링 실행
    if 'searchType' in request.GET and 'searchWord' in request.GET:
        search_type = request.GET['searchType'] # GET안의 문자열은
        search_word = request.GET['searchWord'] # html의 name 속성

        print('search_type: {}, search_word: {}'.format(search_type,search_word))

        # match: java switch랑 비슷
        match search_type:
            case 'title': # 검색기준이 제목일 때
                result = Board.objects.filter(title__contains = search_word)
            case 'writer': # 검색기준이 글쓴이일 때
                result = Board.objects.filter(writer__contains = search_word)
            case 'content': # 검색기준이 내용일 때
                result = Board.objects.filter(content__contains = search_word)

        # 검색을 했을때만 검색 기준과 키워드를 context에 넣는다
        context['searchType'] = search_type
        context['searchWord'] = search_word
    else : #QueryDict에 검색조건과 키워드가 없을 때
        result = Board.objects.all()

    # 검색 결과 또는 전체 목록을 id의 내림차순 정렬
    result = result.order_by('-id')  

    # 페이징 넣기
    # Paginator(목록, 목록에 보여줄 개수)
    paginator = Paginator(result, 10)

    # Paginator 클래스를 이용해서 자른 목록의 단위에서
    # 몇 번째 단위를 보여줄 것인지 정한다
    page_obj = paginator.get_page(request.GET.get('page'))
    
    # context['board_list'] = result
    # 페이징한 일부 목록을 반환
    context['page_obj'] = page_obj
    
    return render(request, 'board/index.html', context)

def read(request, id):
    print('id=', id)

    board = Board.objects.get(id = id)
    reply_list = Reply.objects.filter(board_obj = id).order_by('-id')
    # 조회수
    board.view_count = board.view_count + 1
    board.save()

    context = {
        'board':board,
        # 'replyList' : reply_list
    }

    return render(request, 'board/read.html', context)


def home(request):
    return HttpResponseRedirect('/board/')

# 내가 따로 만든 로그인 url이 있다면 login_url 키워드 변수를
# 지정해야한다.
@login_required(login_url='common:login')
def write(request):

    if request.method == 'GET':  # 요청 방식이 GET이면 화면 표시
        return render(request, 'board/board_form.html')
    
    else:  # 요청 방식이 POST면
        # DB저장
        print(request.POST)
        print(request.FILES)
        title = request.POST['title']
        content = request.POST['content']
        author = request.user # 요청에 들어있는 User 객체
        

        # 객체.save()
        board = Board(
            title = title,
            author = author,
            content = content
        )
        # get 메서드 사용하는 이유
        # 딕셔너리에서 존재하지 않는 키를 딕셔너리[키] -> KeyError
        # 딕셔너리.get("키")
        if request.FILES.get("uploadFile"):
            upload_file = request.FILES["uploadFile"]
            #요청에 들어있던 처부파일을 모델에 설정
            board.attached_file = upload_file
            board.original_file_name = upload_file.name
        board.save() # DB에 insert
        
        # # 모델.object.create(값)
        # Board.objects.create(
        #     title = title,
        #     author = author,  # User 객체 저장
        #     content = content
        # )
        return HttpResponseRedirect('/board/')
    
@login_required(login_url='common:login')
def update(request, id):
    
    board = Board.objects.get(id = id)

    if request.method == 'GET' and board.author.username == request.user.username:
        context = {'board': board }
        return render(request, 'board/board_update.html', context)
    else:
        if board.author.username == request.user.username :
            board.title = request.POST['title']
            board.content = request.POST['content']
            # 첨부파일이 있다면
            if request.FILES.get('uploadFile'):
                upload_file =request.FILES['uploadFile']
                #요청에 들어있던 처부파일을 모델에 설정
                board.attached_file = upload_file
                board.original_file_name = upload_file.name
            else:# 첨부파일이 없다면
                board.attached_file = None
                board.original_file_name = None
            board.save()

    return HttpResponseRedirect('/board/')

@login_required(login_url='common:login')
def delete(request, id):
    print(id)
    # 해당 객체를 가져옴
    board = Board.objects.get(id = id)
    # 글 작성자의 id와 접속한 사람의 id가 같을 때
    if board.author.username == request.user.username :
        board.delete()
    # 다를 때
    return HttpResponseRedirect('/board/')

def write_reply(request, id) :
    data = request.POST
    user = request.user
    reply = loads(request.body) # 요청의 body를 해석
    reply_text = reply['replyText']

    # queryset을 이용
    board = Board.objects.get(id = id)
    board.reply_set.create(
        reply_content = reply_text,
        user = user
    )
    return JsonResponse({'result': 'success'})

def delete_reply(request, id) :
    rid = (loads(request.body))['rid']
    Board.objects.get(id = id ).reply_set.get(id = rid).delete()
    # Reply.objects.get(id = rid).delete
    return HttpResponse(status=200)

def update_reply(request, id) :
    board = Board.objects.get(id = id)

    if request.method == 'GET' :
        data = request.GET
        rid = data['rid']
        reply = board.reply_set.get(id=rid)
        return JsonResponse({'replyText': reply.reply_content})
    else :
        data = loads(request.body)
        rid = data['rid']
        replyText = data['replyText']
        reply = board.reply_set.get(id = rid)
        reply.reply_content = replyText
        reply.save()
        return HttpResponse(status=200)
    
def call_ajax(request) :
    print('성공한 것 같아요')

    data = loads(request.body)
    print('템플릿에서 보낸 데이터',data)
    print(data['txt'])
    print(type(data))
    return JsonResponse({'result' : 'ㅊㅋㅊㅋ'})

def load_reply(requst,id):

    reply_list = Board.objects.get(id=id).reply_set.all()
    reply_dict_list = []
    # reply_list의 정보를 가지고 dictionary 만들기
    for reply in reply_list:
        reply_dict = {
            'id': reply.id,
            'username': reply.user.username,
            'replyText': reply.reply_content,
            'inputDate': reply.input_date
        }
        reply_dict_list.append(reply_dict)
    
    context = {'replyList': reply_dict_list}

    return JsonResponse(context)

def downlad(requst,id):
    board = Board.objects.get(id=id)
    attached_file = board.attached_file
    original_file_name = board.original_file_name
    # 글 번호에 달려있던 첨부파일로 파일형식 응답 객체 생성
    response =FileResponse(attached_file)
    response['Content-Disposition'] = 'attachment; filename=%s' %original_file_name
    return response

# Class Base
class BoardList(ListView):
    # ListView : 목록을 보여주는 기능
    # model = 이 페이지에서 표시할 객체 타입
    model = Board
    # ordering 속성에는 문자열로 내가 정렬하고 싶은 열 이름을 쓴다
    # 열 이름 앞에 -가 붙어 있으면 내림차순 정렬
    ordering = '-id'
    # 클래스 기반 뷰에서 사용하는 템플릿은
    # 일반적으로 이름이 객체이름_list.html

class BoardDetail(DetailView):
    model = Board
    # template_name 속성 : 내가 별도로 이요하고 싶은 템플릿 파일이 있을 때
    # 해당 파일 이름을 지정
    # template_name을 사용하지 않으면 model이름_detail.html을 찾아간다.
    template_name = 'board/read.html'

projects/myboard/templates/board/board_form.html
{# common/base.html을 상속받겠음 #}
{% extends 'common/base.html' %}
{% block title %}[글쓰기]{% endblock title%}

{% block body %}
<h1>글쓰기</h1>
<!-- 상위 디렉토리로 이동한 후에 write/ 호출 -->
<form action="{% url 'board:write' %}" method="post" enctype="multipart/form-data" onsubmit="return formValidate();">
  {% csrf_token %}

  <table>
    <tr>
      <th>제목</th>
      <td><input type="text" name="title" id="title" /></td>
    </tr>

    <!-- 세션에 writer가 없으면 해당 tr 표시 -->
    <!-- writer가 있으면 해당 tr 표시 안됨 -->
    <!-- {% if not request.session.writer %}
    <tr>
      <th>글쓴이</th>
      <td><input type="text" name="writer" /></td>
    </tr>
    {% endif %} -->

    <tr>
      <th>내용</th>
      <td><textarea name="content" id="content" cols="30" rows="10"></textarea></td>
    </tr>
    <tr>
      <th>파일첨부</th>
      <td><input type="file" name="uploadFile"></td>
    </tr>
    <tr>
      <th colspan="2">
        <input type="submit" value="글쓰기" />
      </th>
    </tr>
  </table>
</form>
{% endblock body %}

projects/myboard/templates/board/board_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>CBV로 객체 가져오기</h1>
    <!-- 클래스 기반에서는 기본적으로 리스트 이름을 객체이름_list로 사용 가능 -->
    {% for board in board_list %}
        <a href="{{board.id}}/"><span>{{board.id}} {{board.title}}</span></a>
         <br>
    {% endfor %}
</body>
</html>

projects/myboard/templates/board/board_update.html
{# common/base.html을 상속받겠음 #}
{% extends 'common/base.html' %}
{% block title %}[글 수정하기]{% endblock title%}
{% block body %}
  <script>
    function validate() {
      
      let fomResult = formValidate();
      let fileResult = validateFile();
      if (fomResult && validateFile()){
        return true;
      }
      return false;
    }
    function validateFile() {
      let file = document.getElementById("uploadFile");
      console.log(file.value);
      // 첨부파일이 있었는데 수정하면서 없을 때
      if ('{{board.original_file_name}}' !== "" && file.value === ""){
        let go = confirm("파일이 첨부되지 않았습니다. 계속하시겠습니까?")
        if (go == true){
          return true;
        }else{
          return false;
        }
      }
    }
  </script>
<h1>글 수정하기</h1>

<form action="{% url 'board:update' board.id %}" method="post" enctype="multipart/form-data" onsubmit="return validate();">
  {% csrf_token %}
  <table>
    <tr>
      <th>제목</th>
      <td><input type="text" name="title" id="title" value="{{ board.title }}"/></td>
    </tr>
    <!-- <tr>
      <th>글쓴이</th>
      <td>
        <input type="text" name="writer" value="{{ board.writer }}" />
      </td>
    </tr> -->
    <tr>
      <th>내용</th>
      <td>
        <textarea name="content" id="content" cols="30" rows="10">{{board.content}}</textarea>
      </td>
    </tr>

    <tr>
        <th>첨부파일</th>
        <td>
          현재 첨부파일 :
          {% if board.original_file_name %}
            {{board.original_file_name}}
          {% else %}
            없음
          {% endif %}
          <input type="file" name="uploadFile" id="uploadFile" value="{{board.original_file_name}}">
        </td>
    </tr>

    <tr>
      <th colspan="2">
        <input type="submit" value="수정하기" />
      </th>
    </tr>
  </table>
</form>
{% endblock body %}

projects/myboard/templates/board/index.html
{# common/base.html을 상속받겠음 #}
{% extends 'common/base.html' %}
{% block title %}[게시판]{% endblock title%}

{% block body %}
<style>
  
#count{
  font-size: small;
  color: blueviolet;
}
</style>
<script>
  $(document).ready(function(){

    });
  function callFunction(){
    let data = {'txt' : 'hello'};
    // AJAX로 서버와 통신을 할 때에도
    // CSRF토큰은 있어야 한다
    $.ajax({
      url : '/board/callAjax/',
      type : 'post',
      headers : {'X-CSRFTOKEN': '{{csrf_token}}'},
      data : JSON.stringify(data), // JS객체를 문자열화 
      success : function(res){
        console.log(res);
        console.log(res['result']);
        console.log(res.result);
        console.log('성공했음');
      }
    });
  }
</script>
  <h1>게시판</h1>
  {% if user.is_authenticated %}
  <a href="{% url 'board:write' %}">글쓰기</a>
  {% endif %}
  <input type="button" value="눌러보세요" onclick="callFunction();">
  <div id="result"></div>
  {% if page_obj %}
  <table border="1">
    <tr>
      <th>번호</th>
      <th>제목</th>
      <th>글쓴이</th>
      <th>작성일</th>
      <th>조회수</th>
    </tr>
    {% for board in page_obj %}
    <tr>
      <td>{{ board.id }}</td>
      <td>
        <!-- 파라미터가 있는 주소를 호출할 때 -->
        <!-- name뒤에 한 칸 띄우고 파라미터 값 지정 -->
        {% if board.original_file_name %}
        <img src="/media/{{board.attached_file}}" width="50" height="50" >
        {% endif %}
        <a href="{% url 'board:detail' board.id %}">{{ board.title }}</a>&nbsp;
        <span id="count">[{{board.reply_set.all.count}}]</span>
      </td>
      <td>{{board.author.username}}</td>
      <td>{{ board.input_date }}</td>
      <td>{{ board.view_count }}</td>
    </tr>
    {% endfor %}
  </table>
  {% else %}
  <p>게시글이 존재하지 않습니다.</p>
  {% endif %}
  <!-- 검색하기 -->
  <!-- action을 비워놓게 되면 현재 페이지의 주소를 다시 호출한다 -->
  <form action="">
    <select name="searchType">
      {% if searchType == 'title' %}
      <!-- option selected속성: 초기 선택 지정  -->
      <option value="title" selected="selected">제목</option>
      {% else %}
      <option value="title">제목</option>
      {% endif %} {% if searchType == 'writer' %}
      <option value="writer" selected="selected">글쓴이</option>
      {% else %}
      <option value="writer">글쓴이</option>
      {% endif %} {% if searchType == 'content' %}
      <option value="content" selected="selected">내용</option>
      {% else %}
      <option value="content">내용</option>
      {% endif %}
    </select>
    <input type="text" name="searchWord" value="{{ searchWord}}" />
    <input type="submit" value="검색" />
  </form>
  <!-- 페이징 -->
  {% if page_obj.has_previous %}
  <!-- GET의 parameter(쿼리스트링)은 URL의 구성요소와 별도로 표시-->
  <a href="{% url 'board:index' %}?page=1">&laquo;처음 페이지로</a>
  <a href="{% url 'board:index' %}?page={{ page_obj.previous_page_number }}">이전 페이지로</a>
  {% endif %}

  <!-- paginator의 number 현재 페이지 번호 -->
  <!-- num_pages는 전체 페이지 수 -->
  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

  {% if page_obj.has_next %}
  <a href="{% url 'board:index' %}?page={{ page_obj.next_page_number }}">다음 페이지로</a>
  <a href="{% url 'board:index' %}?page={{ page_obj.paginator.num_pages}}">마지막 페이지로</a>
  {% endif %}
  <br />

  <!-- 페이징2 : 가지고 있는 페이지의 번호 다 보여주기 -->
  {% for page_number in page_obj.paginator.page_range %}
  <a href="{% url 'board:index' %}?page={{ page_number }}">{{ page_number }}</a> &nbsp; {% endfor %}
  <br />

  <!-- 페이징3: 2 개선한 버전 -->
  {% for page_number in page_obj.paginator.page_range %} 
  {% if page_number >= page_obj.number|add:-5 and page_number <= page_obj.number|add:5 %}
    {% if searchWord %}
      <a href='{% url "board:index" %}?page={{ page_number }}&searchType={{ searchType }}&searchWord={{ searchWord }}'>{{ page_number }}</a>
    {% else %}
      {% if page_number == page_obj.number %}
        <a href="{% url 'board:index' %}?page={{ page_number }}" class="color">{{ page_number }}</a>
      {% else %}
        <a href="{% url 'board:index' %}?page={{ page_number }}">{{ page_number }}</a>
      {% endif %}
    {% endif %}
  {% endif %} 
  {% endfor %}
{% endblock body%}

projects/myboard/templates/board/read.html
{# common/base.html을 상속받겠음 #}
{% extends 'common/base.html' %}
{% block title %}[게시판]{% endblock title%}

{% block body %}
<script>
  function showUpdateForm(param){
    $("#writeForm").hide();
    $("#updateForm").show();

    $.ajax({
      url: '{% url "board:update_reply" id=board.id %}',
      type: 'get',
      data: {'rid': param},
      success: function(res){
        $("#replyTextUpdate").val(res.replyText);
        $("#rid").val(param);
      }
    });
  }
  
  function updateReply(){
    let rid = $("#rid").val();
    let replyText = $("#replyTextUpdate").val();
    let data = {'rid': rid, 'replyText': replyText};
    if (replyText.length === 0){
      alert('댓글이 비어있음')
      return;
    }
    $.ajax({
      url: '{% url "board:update_reply" id=board.id %}',
      type : 'post',
      headers : {'X-CSRFTOKEN': '{{csrf_token}}'},
      data: JSON.stringify(data),
      success: function(res){
        $("#replyTextUpdate").val("");
        $("#updateForm").hide();
        $("#writeForm").show();
        loadReplyList();
      }
    });
  }

  function writeReply(){
    let replyText = $("#replyTextWrite").val();
    let data = { 'replyText': replyText }
    if (replyText.length === 0){
      alert('댓글이 비어있음')
      return;
    }
    $.ajax({
      url: '{% url "board:write_reply" id=board.id %}',
      type : 'post',
      headers : {'X-CSRFTOKEN': '{{csrf_token}}'},
      data : JSON.stringify(data),
      success : function(result){
        $("#replyTextWrite").val("");
        loadReplyList();
      }
    });
  }
  
  function deleteReply(param){
    let data = {'rid': param};
    $.ajax({
      url: '{% url "board:delete_reply" id=board.id %}',
      type : 'post',
      headers : {'X-CSRFTOKEN': '{{csrf_token}}'},
      data: JSON.stringify(data),
      success : function(response){
        loadReplyList();
      }
    });
  }

  $(document).ready(function(){
    $("#updateForm").hide();
    loadReplyList();

    $("#btnWrite").click(function(){
      writeReply();
    });
    
    $("#btnUpdate").click(function(){
      updateReply();
    });

  });

  function loadReplyList(){
    $.ajax({
      url: '{% url "board:load_reply" id=board.id %}',
      type: 'get',
      success: function(res){
        // console.log(res)
        let str = '<table>';
        $.each(res.replyList, function(index, item){
          let replacedDate = item.inputDate.replace("T"," ").replace("Z","").split(".")[0]
          str += "<tr>";
          str += "<td>" + item.replyText + "</td>";
          str += "<td>" + item.username + "</td>";
          str += "<td>" + replacedDate + "</td>";
          str += "<td>"
          if('{{user.username}}' === item.username){
            str += "<a href='#' onclick = 'showUpdateForm("+ item.id +")'>수정</a>";
            str += "<a href='#' onclick = 'deleteReply("+ item.id +")'>삭제</a>";
          }
          str += "</td>"
          str += "</tr>";
        });
        str += "</table>";
        $("#replyList").html(str);
      }
    });
  }
</script>
<h1>글 보기</h1>
<table>
  <tr>
    <th>{{ board.id }}</th>
    <th>{{ board.title }}</th>
    <td>{{ board.view_count }}</td>
  </tr>
  <tr>
    <td colspan="2">{{ board.input_date|date:'y.m.d H:i' }}</td>
    <td>{{ board.writer }}</td>
  </tr>
  <tr>
    <td colspan="4">{{ board.content }}</td>
  </tr>
  {% if board.original_file_name %}
  <tr>
    <th>첨부파일</th>
    <td colspan="3">
        <a href="{% url 'board:downlad' id=board.id %}">{{board.original_file_name}}</a>
    </td>
  </tr>
  {% endif %}
</table>
<!-- 수정/삭제 -->
<!-- username끼리 비교하려면 -->
{% if board.author.username == user.username %}
<a href="{% url 'board:update' board.id %}">수정</a> /
<a href="{% url 'board:delete' board.id %}" onclick="javascript: return confirm('정말 삭제 하시겠어요?')">삭제</a>
{% endif %}
<div id = 'replyArea'>
  <!-- 댓글 목록 표시할 곳 -->
  <div id="replyList">
    <!-- board 객체 뿐만 아니라 board와 FK로 엮인 객체는 -->
    <!-- board.모델이름_set으로 가져올 수 있다 -->
  </div>
  <!-- 댓글 입력 폼 -->
  <div id="replyForm">
    <div id="writeForm">
      <textarea id="replyTextWrite"></textarea>
      <input type="button" id="btnWrite" value="댓글쓰기">
    </div>
    <div id="updateForm">
      <input type="hidden" id="rid">
      <textarea id="replyTextUpdate"></textarea>
      <input type="button" id="btnUpdate" value="댓글수정">
    </div>
  </div>
</div>
<form action="{% url 'board:index' %}">
  <input type="submit" value="목록으로" />
</form>
{% endblock body %}