projects/myboard/board/urls.py
from django.urls import path

from.import views
app_name = 'board'
urlpatterns = [
    # board/라면
    path('', views.index, name='index'),
    # 글읽기 주소 /board/0
    path('<int:id>/', views.read, name='detail'),
    # 글쓰기 주소
    path('write/', views.write, name='write'),
    # 수정 주소
    path('<int:id>/update/', views.update, name='update'),
    # 삭제 주소
    path('<int:id>/delete/', views.delete, name='delete'),
    # 댓글쓰기 주소
    path('<int:id>/write_reply/', views.write_reply, name = 'write_reply'),
    # 댓글 삭제 주소(id: 글번호, rid: 댓글번호)
    path('<int:id>/delete_reply/', views.delete_reply, name='delete_reply'),
    # 댓글 수정 주소
    path('<int:id>/update_reply/', views.update_reply, name='update_reply'),

    # AJAX
    path('callAjax/', views.call_ajax),
    
    # AJAX_댓글 목록
    path('<int:id>/load_reply/',views.load_reply, name = 'load_reply'),
    path('<int:id>/downlad/',views.downlad,name='downlad'),


    # CBV 방식으로 호출할 주소
    # as_view() : 클래스를 뷰의 기능으로서 사용하겠다~
    path('cbv/', views.BoardList.as_view()),
    path('cbv/<int:pk>/', views.BoardDetail.as_view()),
]

projects/myboard/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view

# 현재 폴더에서 views.py를 가지고 오는데 그 이름이 common_view
from . import views as common_view

app_name = 'common'

urlpatterns = [
    path('', common_view.index,name='index'),
    path('login/', auth_view.LoginView.as_view(template_name = 'common/login.html'),
         name='login'),
    path('logout/', auth_view.LogoutView.as_view(), name='logout'),

    # 회원가입
    # path('signup/', common_view.signup),
    path('signup/', common_view.signup_custom, name='signup'),
    # 회원정보보기
    path('info/', common_view.info,name='info'),
    # 회원삭제
    path('delete/', common_view.delete, name =  'delete'),
    # 회원수정
    path('update/', common_view.update, name = 'update'),

]

projects/myboard/myboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings # 현재 프로젝트의 sttings.py
from django.conf.urls.static import static

urlpatterns = [
    path('', include('common.urls')),
    path("admin/", admin.site.urls),
    path('board/', include('board.urls')),
    
] + static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

projects/myboard/common/models.py
from django.db import models

# Create your models here.

projects/myboard/common/forms.py
# forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

# UserCreationForm을 상속받는 UserForm을 작성
class UserForm(UserCreationForm):
    email = forms.EmailField(label = '이메일')
    first_name = forms.CharField(max_length=10,label = '이름')
    last_name = forms.CharField(max_length=10,label='성')

    class Meta : # 폼의 정보를 담고 있는 내부 클래스
        model = User
        fields = ('username','email','first_name','last_name')
class CustomChangeForm(UserChangeForm) :
    
    class Meta :
        model = User
        fields = ('email', 'first_name', 'last_name')
        

projects/myboard/common/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
# 장고가 제공하는 기본 회원가입 폼
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required

# 우리가 만든 커스텀 회원 폼
from .forms import UserForm, CustomChangeForm

# Create your views here.
def index(request):

    return render(request, 'common/index.html')

def signup(request):
    if request.method == 'POST':
        #요청 객체가 담고있는 정보로 사용자 생성 폼 만든다
        print(request.POST)
        form = UserCreationForm(request.POST)

        if form.is_valid(): #폼의 내용이 유효하다면
            form.save() #db에 폼 정보 저장

            # 폼에 입력한 값 가져오기
            username = form.cleaned_data.get('username')
            row_password = form.cleaned_data.get('password1')

            # 사용자 인증
            user = authenticate(username = username, password = row_password)
            # 로그인
            login(request, user)

            return redirect('/')
    else:
        # get방식으로 요청이오면 비어있는 사용자 생성 폼을 만든다
        form = UserCreationForm()
    return render(request, 'common/signup.html', {'form':form})

def signup_custom(request) :
    if request.method == 'POST' :
        print(request.POST) # QueryDict 한 번 보기
        # request.POST에 들어있는 정보를 UserForm 형식으로 변환
        form = UserForm(request.POST)

        # form이 유효한가?
        if form.is_valid() :
            form.save() # 폼의 내용을 DB(auth_user)에 바로 저장
            # 폼 정보 취득
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            last_name = form.cleaned_data.get('last_name')
            first_name = form.cleaned_data.get('first_name')
            # 사용자 인증 후 로그인
            user = authenticate(
                username = username, 
                password = raw_password,
                last_name = last_name,
                first_name = first_name,
                )
            login(request, user)

            return redirect('/') # 로그인 하고 메인 페이지로 넘김
    else : # 요청이 GET일때
        form = UserForm() # 새 폼 만들어주기
    return render(request,'common/signup.html', {'form':form})

def delete(request) : 
    
    if request.user.is_authenticated:
        request.user.delete() # user 정보 삭제

    # render나 redirect의 파라미터로 app_name:url_name 작성 가능
    return redirect('common:index')
    
def update(request) :
    if request.method == 'POST' :
        form = CustomChangeForm(request.POST, instance =request.user)

        if form.is_valid() :
            form.save() # form이 유효하다면 해당 내용 저장
            return redirect('common:index')
    else :
        # CustomChangeForm(instance) 보내면 django가 제공하는 기본 폼 사용할 수 있음
        form = CustomChangeForm()

    return render(request, 'common/update.html', {'form' : form})

def info(request) :
    
    return render(request,'common/info.html')

projects/myboard/templates/common/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- 틀이 되는 템플릿의 title이 덮어써지지 않도록 -->
    <title>{% block title%}{% endblock title %}</title>
    <!-- 스타일 import -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'script.js' %}"></script>
</head>
<body>
     <!-- 내가 넣고 싶은 조각(frafment)을 include -->
     {% include 'common/menubar.html'%}
    <!-- 다른 내용을 삽입할 자리 만들기 -->
    {% block body %}{% endblock body %}
</body>
</html>

projects/myboard/templates/common/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>안녕하세요</h1>
    <!-- django에서 제공하는 user모델 -->
    <h2>
      Hello, {% if user.is_authenticated %}
      <!-- 유저 정보가 있으면 username 표시 -->
      {{ user.username }} {% else %} GUEST {% endif %}
    </h2>

    <ul>
      {% if not user.is_authenticated %}
      <li>
        <a href="{% url 'common:signup' %}">회원가입</a>
      </li>
      <li>
        <a href="{% url 'common:login' %}">로그인</a>
      </li>
      {% else %}
      <li>
        <a href="{% url 'common:logout' %}">로그아웃</a>
      </li>
      <li>
        <a href="{% url 'common:info' %}">회원정보보기</a>
      </li>
      {% endif %}
      <li>
        <a href="{% url 'board:index' %}">게시판으로 가기</a>
      </li>
      <!--CBV 호출-->
      <li>
        <a href="/board/cbv/">게시판(CBV)</a>
      </li>
    </ul>
  </body>
</html>

projects/myboard/templates/common/info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <table border="1">
        <tr>
            <th>아이디</th>
            <td>{{user.username}}</td>
        </tr>
        <tr>
            <th>성</th>
            <td>
                {{user.last_name}}
            </td>
        </tr>
        <tr>
            <th>이름</th>
            <td>
                {{user.first_name}}
            </td>
        </tr>
        <tr>
            <th>이메일</th>
            <td>
                {{user.email}}
            </td>
        </tr>
    </table>
    <a href="{% url 'common:update' %}">회원정보수정</a>
    <a href="{% url 'common:delete' %}" onclick="javascript: return confirm('정말 삭제 하시겠어요?')">회원정보삭제</a>
</body>
</html>

projects/myboard/templates/common/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>로그인</h1>
    <form action="{% url 'common:login'  %}" method="post">
        {% csrf_token %}
        <!-- 로그인 성공 후 이동할 URL -->
        <input type="hidden" name="next" value="{{next}}">
        <table>
            <tr>
                <th>아이디</th>
                <td><input type="text" name="username"></td>
            </tr>
            <tr>
                <th>비밀번호</th>
                <td><input type="password" name="password"></td>
            </tr>
            <tr>
                <th colspan="2"><input type="submit" value="로그인"></th>
            </tr>
        </table>
    </form>
</body>
</html>

projects/myboard/templates/common/menubar.html
<!-- vscode에서 .하고 자동완성하면 -->
<div>
    <a href="/">홈</a>&nbsp;&nbsp;
    {% if not user.is_authenticated %}
    <a href="{% url 'common:signup' %}">회원가입</a>&nbsp;&nbsp;
    <a href="{% url 'common:login' %}">로그인</a>&nbsp;&nbsp;
    {% else %}
    <span>{{user.username}}</span>&nbsp;&nbsp;
    <a href="{% url 'common:logout' %}">로그아웃</a>&nbsp;&nbsp;
    {% endif %}
    <!-- 아래의 호출법은 주소를 하드코딩하는게 아니라 -->
    <!-- urls.py에 정의된 name속성을 통해서 이동 -->
    <a href="{% url 'board:index' %}">게시판으로 이동</a>
</div>

projects/myboard/templates/common/signup.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>회원가입</h1>
    <form action="../signup/" method="post">
      {% csrf_token %}
      <table>
        <!-- 각 태그에 적용한 name속성은 UserCreationForm에서 제공하는 필드 이름과 같다 -->
        <tr>
          <!-- 아이디 -->
          <th>아이디</th>
          <td>
            <input type="text" name="username" />
          </td>
        </tr>
        <tr>
          <!-- 비밀번호 -->
          <th>비밀번호</th>
          <td>
            <input type="password" name="password1" />
          </td>
        </tr>
        <tr>
          <!-- 비밀번호 확인 -->
          <th>비밀번호 확인</th>
          <td><input type="password" name="password2" /></td>
        </tr>
        <tr>
          <!--이메일-->
          <th>이메일 확인</th>
          <td><input type="email" name="email" /> <br /></td>
        </tr>
        <tr>
          <!--이름-->
          <th>성</th>
          <td><input type="text" name="last_name" /></td>
        </tr>
        <tr>
          <th>이름</th>
          <td><input type="text" name="first_name" /></td>
        </tr>
        <tr>
          <th colspan="2">
            <input type="submit" value="회원가입" />
          </th>
        </tr>
      </table>
    </form>
  </body>
</html>

projects/myboard/templates/common/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'common:update' %}" method="post">
        {% csrf_token %}
        <table>
            <tr>
                <th>아이디</th>
                <td>{{user.username}}</td>
            </tr>
            <tr>
                <th>성</th>
                <td>
                    <input type="text" name="last_name" value="{{user.last_name}}">
                </td>
            </tr>
            <tr>
                <th>이름</th>
                <td>
                    <input type="text" name="first_name" value="{{user.first_name}}" >
                </td>
            </tr>
            <tr>
                <th>이메일</th>
                <td>
                    <input type="text" name="email" value="{{user.email}}">
                </td>
            </tr>
        </table>
        <input type="submit" value="정보수정">
    </form>
</body>
</html>